config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#top'

 devise_for :hosts, controllers: {
  #get "sign_in", to: "devise/sessions"
  sessions:      'hosts/sessions',
  passwords:     'hosts/passwords',
  registrations: 'hosts/registrations'
}

  devise_for :users, controllers: {
   sessions: 'users/sessions',
   passwords: 'users/passwords',
   registrations: 'users/registrations'
}

  resources :users, only: [:show, :edit, :update]
  resources :hosts, only: [:show, :edit, :update]
  resources :events do
  resources :joins, only: [:create, :destroy]
  end
  resources :articles do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_pictures, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :users, through: :likes, source: :article
    accepts_attachments_for :article_pictures, attachment: :picture
    geocoded_by :address
    after_validation :geocode
    acts_as_taggable
    enum category:{report: 0,item: 1,coodinate: 2}
    attachment :main_picture
    with_options presence: true do
      validates :title, length: { maximum: 30 }
      validates :body, length: { maximum: 1000 }
      validates :main_picture
    end
    # ユーザーが持っているlikeモデルを探す
    def like_user(user_id)
        likes.find_by(user_id: user_id)
    end
    default_scope -> { order(created_at: :desc) }
    # 時間の降順に表示
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    #タグ絞り込み tagged_withメソッド
    if params[:tag_name].present?
      @articles = Article.tagged_with([params[:tag_name]])
    else
      @articles = Article.all
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find_by(id: params[:id])
    @user = @article.user
    @latitude = @article.latitude
    @longitude = @article.longitude
    @address = @article.address
    @comment = Comment.new
    @comments = @article.comments
  end

  # GET /articles/new
  def new
    @article = Article.new
    @article.article_pictures.build
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find_by(id: params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    @article.tag_list = article_params[:tag_list]
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:date, :title, :body, :country, :category, :address, :latitude, :longitude, :tag_list, :main_picture, article_pictures_pictures: [])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
	include ActsAsTaggableOn::TagsHelper
end

app/views/articles/_form.html.erb
<div class="row">
  <div class="col-lg-8 col-md-6 ml-auto mr-auto mb-5">

    <%= form_with(model: article, local: true) do |form| %>
      <% if article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
          <% article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="date">
        <%= form.label :"日付をお選び下さい" %>
        <%= form.date_select :date %>
      </div>

      <div class="field">
        <%= form.label :"タイトル" %>
        <%= form.text_field :title, :size => "60x10" %>
      </div>

      <div class="field">
        <%= form.label :"テキスト　1000文字以内" %>
        <%= form.text_area :body, :size => "60x10" %>
      </div>

      <div class="field">
        <%= form.label :"国名" %>
        <%= form.country_select :country, format: :with_alpha2, selected: "JP" %>
      </div>

      <div class="field">
        <%= form.label :"カテゴリー" %>
        <%= form.select :category, Article.categories.keys.map {|k| [I18n.t("enums.article.category.#{k}"), k]} %>
      </div>

      <div class="field"> 
        <%= form.label :"タグ付け（複数タグ付けする場合タグのワードを , で区切ってください)" %>
        <%= form.text_field :tag_list, value: @article.tag_list.join(','), class: "form-control", "data-role" => "tagsinput" %>
      </div>

      <div class="field">
        <%= form.label :"表示するマップの住所/施設名" %>
        <%= form.text_field :address %>
      </div>

      <div class="field">
        <%= form.label :"サムネイル表示画像" %>
        <%= form.attachment_field :main_picture %>
      </div>

      <div class="field">
        <%= form.label :"記事に写真を追加する(複数選択可)" %>
        <%= form.attachment_field :article_pictures_pictures, multiple: true %>
      </div>


      <div class="actions">
            <%= form.submit 'post article', class: "btn btn-primary btn-sm ml-2"%>
      </div>
    <% end %>

  </div>
</div>

app/views/articles/_tag_list.html.erb
  	<span class="badge badge-primary.mr-1.p-2"><%= raw(article.tag_list.map { |t| link_to t, articles_path(t) }.join(', ')) %></span>

<%= tag_list.each do |tag| %>
    <%= link_to tag, articles_path(tag_name: tag), class: "badge badge-primary.mr-1.p-2" %>
    <!-- tag_nameにarticle.tag_listで取り出したタグをパラメータとして渡す -->
<% end %>

<%= link_to tag, articles_path({ :action => :tag_name, :id => tag }) %>

app/views/articles/edit.html.erb
<div class="container">
  <div class="form">
    <%= render 'form', article: @article %>
  </div>

  <div class="row">
    <div class="col-lg-8 col-md-6 ml-auto mr-auto mb-5">
      <%= link_to '<< Back articles', articles_path, class: "btn btn-primary btn-sm ml-2"%>
      <%= link_to 'read article', @article, class: "btn btn-primary btn-sm ml-2"%>
    </div>
  </div>

</div>

    

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
 <div class="form">

  <div class="row">
    <div class="col-xs-12 center-block display-3">All Articles</div>
  </div>

　<div class="row">

    <% @articles.each do |article| %>
     <div class="col-xs-6 col-lg-3 text-center mb-4">

　　　<div class="card-columns">
      <%= link_to article do %>
      <div class="card" style="width: 15rem;">
        <div class="card-img-top">
          <%= attachment_image_tag article, :main_picture, fallback: "no_image.jpg", class: "img-fluid mx-auto rounded-top"%>
        </div>

        <div class="card-body">
          <%= article.title.truncate(25) %>
          <p class="card-text"><%= simple_format article.body.truncate(60) %></p>
          <div><% article.tag_list.each do |tag| %>
            <%= link_to tag, articles_path(tag_name: tag), class: "badge badge-primary" %>
            <!-- tag_nameにarticle.tag_listで取り出したタグをパラメータとして渡す -->
          <% end %>
          </div>
        </div>

        <div class="card-footer">
          <div class="badge badge-pill badge-secondary btn-sm ml-2"><%= article.address %></div>
          <div class="badge badge-pill badge-secondary btn-sm ml-2"><%= article.category %></div>
        </div>
      </div>
      <% end %>
     </div>

     </div>
    <% end %>

  </div>


 </div>
</div>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Article', new_article_path %>
<% end %>

app/views/articles/new.html.erb
<div class="container">
  <div class="form">

   <%= render 'form', article: @article %>

   <%= link_to 'Back', articles_path %>

  </div>
</div>

app/views/articles/show.html.erb
<script type="text/javascript">
    function initMap() {

        var test ={lat: <%= @latitude %>, lng: <%= @longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: test
        });
        var transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);

        var contentString = '住所：<%= @address %>';
        var infowindow = new google.maps.InfoWindow({
            content: contentString
        });

        var marker = new google.maps.Marker({
            position:test,
            map: map,
            title: contentString
        });

        marker.addListener('click', function() {
            infowindow.open(map, marker);
        });
    }
</script>

<p id="notice"><%= notice %></p>

<div class="container">
  <div class="form">

  <div class="row">
  <div class="col-lg-10 col-md-10 ml-auto mr-auto">


    <div class="row align-items-end">
      <div class="col-md-2">

       <%= link_to user_path(@user.id) do %>
        <p><%= attachment_image_tag @user, :image, fallback: "no_image.jpg", size: '350x150', 
    class: "rounded-circle img-fluid d-block mx-auto"%></p>

         <div class="text text-center ">
           <p>投稿者:<%= @user.webname %></p>
         </div>
       <% end %>

       <div id="likes_buttons_<%= @article.id %>">
         <%= render partial: 'likes/like', locals: { article: @article, likes: @likes} %>
       </div>

     </div>
     <div class="col-md-10">
       <%= attachment_image_tag @article, :main_picture, format: 'jpeg', size: '600x300', class: "rounded img-fluid d-block mx-auto mb-5", fallback: "no_image.jpg" %>
     </div>
　　</div>


    <div class="card text-center">

    <div class="card-header">
      <h4><%= @article.title %></h4>
    </div>

    <div class="card-body">
      <p>
        <%= simple_format @article.body %>
      </p>
    </div>

    <div class="card-footer">
    <p>
      <strong>Date:</strong>
      <%= @article.date %>
    </p>

    <p>
      <strong>Country:</strong>
      <%= @article.country %>
    </p>

    <p>
      <strong>Category:</strong>
      <%= @article.category %>
    </p>

    <p>
      <strong>Tags:</strong>
       <% @article.tag_list.each do |tag| %>
        <%= link_to tag, articles_path(tag_name: tag), class: "badge badge-primary" %>
        <!-- tag_nameにarticle.tag_listで取り出したタグをパラメータとして渡す -->
       <% end %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @article.address %>
    </p>
    </div>

    <% if @article.article_pictures.present? %>
      <% @article.article_pictures.each do |picture| %>
        <%= attachment_image_tag picture, :picture, format: 'jpeg', size: '200x200', class: "img-thumbnail ml-4 mt-3 mb-3" %>
      <% end %>
    <% end %>


    <style type="text/css">
      #map { height: 400px;
        margin-left:auto;
        margin-right:auto;
        text-align:left;
        width: 80%;}
    </style>
    <div id="map"></div>

    <div>
        <h4 class="text mt-4">コメント</h4>
        <% @comments.each do |comment| %><br/>
            投稿者：<%= comment.user.webname %><br/>
            コメント：<%= comment.message %>
              <% if comment.user == current_user %>
                <p><%= link_to '× post delete', article_comment_path(comment.article_id, comment.id), method: :delete, class: "btn btn-primary btn-sm" %></p>
              <% end %>
            <% end %>
        <% if user_signed_in? %>
          <!-- コメント入力欄をブログの詳細ページに表示するため-->
          <%= render partial: 'comments/form', locals: { comment: @comment, article: @article } %>
        <% end %>
      </div>

    </div>

  </div>
  </div>

 </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-10 col-md-10 text-center ml-auto mr-auto mt-3 mb-3">

     <%= link_to '<< Back', articles_path, class: "btn btn-primary btn-sm ml-2" %>
     <% if user_signed_in? %>
      <% if @user.id == current_user.id %>
        <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-primary btn-sm ml-2" %>
        <%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-primary btn-sm ml-2"%>
      <% end %>
     <% end %>

    </div>
  </div>
</div>