config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#top'

 devise_for :hosts, controllers: {
  #get "sign_in", to: "devise/sessions"
  sessions:      'hosts/sessions',
  passwords:     'hosts/passwords',
  registrations: 'hosts/registrations'
}

  devise_for :users, controllers: {
   sessions: 'users/sessions',
   passwords: 'users/passwords',
   registrations: 'users/registrations'
}

  resources :users, only: [:show, :edit, :update]
  resources :hosts, only: [:show, :edit, :update]
  resources :events do
  resources :joins, only: [:create, :destroy]
  end
  resources :articles do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_pictures, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :users, through: :likes, source: :article
    accepts_attachments_for :article_pictures, attachment: :picture
    geocoded_by :address
    after_validation :geocode
    acts_as_taggable
    enum category:{report: 0,item: 1,coodinate: 2}
    attachment :main_picture
    with_options presence: true do
      validates :title, length: { maximum: 30 }
      validates :body, length: { maximum: 1000 }
      validates :main_picture
    end
    # ユーザーが持っているlikeモデルを探す
    def like_user(user_id)
        likes.find_by(user_id: user_id)
    end
    default_scope -> { order(created_at: :desc) }
    # 時間の降順に表示
end

app/models/article_picture.rb
class ArticlePicture < ApplicationRecord
	belongs_to :article
	attachment :picture
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :article
	validates :message, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  attachment :picture
  belongs_to :host
  has_many :joins, dependent: :destroy, foreign_key: 'Event_id'
  has_many :users, through: :joins, source: :event
  geocoded_by :address
  after_validation :geocode
  default_scope -> { order(date: :desc) }
  # 時間の降順に表示
  with_options presence: true do
    validates :title, length: { maximum: 30 }
    validates :body, length: { maximum: 1000 }
    validates :address
    validates :date
  end
  def join_user(user_id)
    joins.find_by(user_id: user_id)
  end

  include JpPrefecture
     jp_prefecture :prefecture_code
  #prefecture_codeからprefecture_nameに変換する
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/host.rb
class Host < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, dependent: :destroy

  validates :group_name, presence: true, length: { maximum: 15 }
  validates :rep_name, presence: true,  length: { maximum: 15 }
  validates :address, presence: true
  validates :phonenum, presence: true,  length: { maximum: 13 }
end

app/models/join.rb
class Join < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :event, counter_cache: :join_count
  validates :user_id, presence: true
  validates :event_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :article
	belongs_to :article, counter_cache: :like_count
	validates :user_id, presence: true
    validates :article_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  has_many :joins, dependent: :destroy
  has_many :events, through: :joins, source: :user, foreign_key: 'User_id'
  has_many :articles, dependent: :destroy
  has_many :articles, through: :likes, source: :user, foreign_key: 'User_id'
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :webname, presence: true, length: { maximum: 15 }
  validates :profile, length: { maximum: 100 }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host
  before_action :authenticate_host!, only: [:edit, :update]
def show
     @events = Event.where(host_id: @host.id).all
  end

  def edit
  end

  def update
    if current_host == @host

     if @host.update(host_params)
        flash[:success] = 'ユーザー情報を編集しました。'
        redirect_to host_path(@host)
      else
        flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
        render :edit
     end
    end
  end

  private
  def set_host
    @host = Host.find(params[:id])
  end
  def host_params
      params.require(:host).permit(:group_name, :rep_name, :address, :phonenum, :url, :email)
  end
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
	before_action :set_event
  
  def create
    @join =Join.create(user_id: current_user.id, event_id: params[:event_id])
    @joins = Join.where(event_id: params[:event_id])
    @event.reload
  end

  def destroy
    join =Join.find_by(user_id: current_user.id, event_id: params[:event_id])
    join.destroy
    @joins = Join.where(event_id: params[:event_id])
    @event.reload
  end

  private
  def set_event
  	@event = Event.find(params[:event_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_hostsbox.html.erb
<div class="sticky-top">

        <% if !user_signed_in? %>
          <div class="card" style="width: 15rem;">

		  <div class="card-header text-center">主催者様情報</div>

         <div class="card-body">
		    <ul class="list-group list-group-flush">
              <p class="list-group-item">会社名/団体名 :<br> <%= host.group_name %></p>
              <p class="list-group-item">代表者名 :<br> <%= host.rep_name %></p>
              <p class="list-group-item">住所 :<br> <%= host.address %></p>
              <p class="list-group-item">電話番号 :<br> <%= host.phonenum %></p>
              <p class="list-group-item">連絡用メールアドレス :<br> <%= host.email %></p>
              <p class="list-group-item">ホームページURL :<br> <%= host.url %></p>
            </ul>
		  </div>

            <div class="card-footer">
              <% if host_signed_in? %>
          	    <% if host.id == current_host.id %>
                  <p><%= link_to "登録情報編集", edit_host_path(host), class: "btn btn-secondary btn-sm" %></p>
                  <p><%= link_to "イベント記事投稿", new_event_path(host), class: "btn btn-secondary btn-sm" %></p>
                  <span><%= link_to "マイページ", host_path(host), class: "btn btn-secondary btn-sm" %></span>
                <% end %>
              <% end %>
            </div>

		  </div>
		<% end %>
</div>

app/views/home/_mybox.html.erb
<div class="sticky-top">

        <% if !host_signed_in? %>
          <div class="card" style="width: 15rem;">

            <div class="card-header">
              <% if user_signed_in? then %>
                <h5>ようこそ<br><%= current_user.webname %> さん</h5>
              <% else %>
                <h5>ようこそ　ゲスト様</h5>
              <% end %>
            </div>

            <div class="card-body">
              <p class="card-text">
               <% if user_signed_in? then %>
                 <span><%= link_to 'My page', user_path(current_user.id), class: "btn btn-secondary btn-sm mb-2" %></span><br>
                 <span><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-secondary btn-sm mb-2" %></span><br>
                 <span><%= link_to "Profile", edit_user_path(current_user.id), class: "btn btn-secondary btn-sm mb-2" %></span><br>
                 <span><%= link_to 'New Article', new_article_path(current_user.id), class: "btn btn-secondary btn-sm mb-2" %></span>
               <% else %>
                 <%= link_to 'Log in', new_user_session_path, method: :get, class: "btn btn-secondary btn-sm mb-2" %><br>
                 <%= link_to 'New menber', new_user_registration_path, method: :get, class: "btn btn-secondary btn-sm mb-2" %>
               <% end %>
             </p>
            </div>

          </div>
        <% end %>
</div>

app/views/home/top.html.erb
<div class="container">

    <div class="row">

      <div class="col-md-12">
        <div class="main-visual">
        <div class="theTarget">
            <div style="background-image: url(sample24.jpg)">
              <div class="main-visual-content">
                <h3 class="main-visual-text ml-3">週末は宝探しへ...</h3>
              </div>
            </div>
            <div style="background-image: url(sample23.jpg)">
              <div class="main-visual-content">
                <h3 class="main-visual-text ml-3">週末は宝探しへ...</h3>
              </div>
            </div>
            <div style="background-image: url(sample25.jpg)">
              <div class="main-visual-content">
                <h3 class="main-visual-text ml-3">週末は宝探しへ...</h3>
              </div>
            </div>
            <div style="background-image: url(sample26.jpg)">
              <div class="main-visual-content">
                <h3 class="main-visual-text ml-3">週末は宝探しへ...</h3>
              </div>
            </div>
            <div style="background-image: url(sample29.jpg)">
              <div class="main-visual-content">
                <h3 class="main-visual-text ml-3">週末は宝探しへ...</h3>
              </div>
            </div>
        </div>
        </div>
      </div>
    </div><br>

    <div class="row">
       <div class="col-md-3">

       <%= render partial: 'mybox' %>
       <% if host_signed_in? %>
         <%= render partial: '/home/hostsbox', locals: {host: current_host} %>
       <% end %>

      </div>
      <div class="col-md-9 float-right">

              <div class="display-3 mb-4" id="sec1">About
              <h5 class="text-muted">このサイトについて</h5></div>
              <h5 class="text">「Brocante」とはフランス語で「美しいガラクタ」の意味です。<br>
              アンティークほど高価で貴重なわけではないけれど、人と一緒に生活を営んできた痕跡を持ちながら
              形を成す雑貨たちは唯一無二の価値を持つ存在です。<br>
              ここではそんな人の手を渡ってきた雑貨を扱う蚤の市やショップ、イベントの情報を共有できるサイトと
              なっております。<br>
              あなたの地元や近所で行われる催しの情報や、蚤の市で入手したアイテムをぜひ自慢してください！<br>
              <small class="text-muted">※投稿にはメンバー登録が必要となります。</small></h5>

              <div class="row">
                <div class="col-md-4 col-sm-6 text-center mt-4 mb-4">
                   <img class="rounded-circle img-fluid d-block mx-auto" src="/assets/sample04.jpg" alt=""><br>
                   <h3>イベントや出店情報をチェックしよう！</h3>
                   <p>あなたの近所で行われている「蚤の市」の情報をチェックして出かけてみよう！<br>
                   イベント情報をブックマークするとマイページに予定が表示されます！</p>
                </div>

                <div class="col-md-4 col-sm-6 text-center mt-4  mb-4">
                  <img class="rounded-circle img-fluid d-block mx-auto" src="/assets/sample05.jpg" alt=""><br>
                  <h3>みんなでアイテムを自慢し合おう！</h3>
                  <p>「Articles」ではみなさんが蚤の市でゲットした素敵なアイテムの写真を見ることができます。<br>
                  素敵なお部屋のインテリアや可愛いブロカンテの写真をお待ちしております。</p>
                </div>

                <div class="col-md-4 col-sm-6 text-center mt-4  mb-4">
                  <img class="rounded-circle img-fluid d-block mx-auto" src="/assets/sample35.jpg" alt=""><br>
                  <h3>旅行先の蚤の市情報を集めよう！</h3>
                  <p>旅先だから出会える工芸品、特に海外では蚤の市が頻繁に行われています。<br>
                  Brocanteでは現地の方からの貴重なマーケット情報も共有することができますよ！</p>
                </div>
              </div>


            <div class="display-3 mb-4"  id="sec2">to Host
              <h5 class="text-muted">イベント主催者・オーナー様</h5></div>
                <h5 class="text"> 当サイトではイベントを企画されている会社様、団体様の登録をお待ちしております。<br>
                    イベントの内容を投稿して当サイト利用者に向け告知をすることができます<br>
                    是非企画されているフリーマーケットや蚤の市等の情報をお寄せください</h5>

                    <div class="card mb-5" style="width: 40rem;">
                        <div class="card-header">
                         <h5>主催者様専用登録ページ/ログインページはこちら<a class="fas fa-angle-double-down ml-3"></a></h5>
                        </div>
                        <div class="card-body text-center">
                         <% if host_signed_in? then %>
                           <span><%= link_to 'Log-out', destroy_host_session_path, method: :delete, class: "btn btn-info btn-sm mb-2" %></span>
                         <% else %>
                           <% if !user_signed_in? %>
                             <%= link_to 'Host Log-in', new_host_session_path, method: :get, class: "btn btn-info btn-sm mb-2" %>
                             <%= link_to 'New Host', new_host_registration_path, method: :get, class: "btn btn-info btn-sm mb-2" %>
                           <% end %>
                         <% end %>
                        </div>
                   </div>


            <div class="display-3 mb-4"  id="sec3">Infomation
              <h5 class="text-muted ">お問い合わせ</h5></div>
                <h5 class="text">当サイトに関するご質問、お問い合わせはこちらよりお願いいたします。<br>
                    e-mail: brocante@×××××.com<br></h5>
                    <h5 class="text mt-2 mb-5">FOLLOW US <i class="fab fa-instagram ml-4"></i><i class="fab fa-facebook-f ml-4"></i><i class="fab fa-twitter ml-4"></i></h5>
                    <% if user_signed_in? %>
                      <% if current_user.admin_flg == true %>
                        <%= link_to 'Admin Log-in', rails_admin_path, class: "btn btn-info btn-sm mb-2" %>
                      <% end %>
                    <% end %>

          </div>
        </div>


    </div>


</div>