config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#top'

 devise_for :hosts, controllers: {
  #get "sign_in", to: "devise/sessions"
  sessions:      'hosts/sessions',
  passwords:     'hosts/passwords',
  registrations: 'hosts/registrations'
}

  devise_for :users, controllers: {
   sessions: 'users/sessions',
   passwords: 'users/passwords',
   registrations: 'users/registrations'
}

  resources :users, only: [:show, :edit, :update]
  resources :hosts, only: [:show, :edit, :update]
  resources :events do
  resources :joins, only: [:create, :destroy]
  end
  resources :articles do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  attachment :picture
  belongs_to :host
  has_many :joins, dependent: :destroy, foreign_key: 'Event_id'
  has_many :users, through: :joins, source: :event
  geocoded_by :address
  after_validation :geocode
  default_scope -> { order(date: :desc) }
  # 時間の降順に表示
  with_options presence: true do
    validates :title, length: { maximum: 30 }
    validates :body, length: { maximum: 1000 }
    validates :address
    validates :date
  end
  def join_user(user_id)
    joins.find_by(user_id: user_id)
  end

  include JpPrefecture
     jp_prefecture :prefecture_code
  #prefecture_codeからprefecture_nameに変換する
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_host!, only: [:edit, :create, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.where("events.date > ?", DateTime.now).reorder(:date)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @host = @event.host
    @latitude = @event.latitude
    @longitude = @event.longitude
    @address = @event.address
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.host_id = current_host.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:host_id, :date, :title, :body, :picture, :prefecture_name, :address, :latitude, :longitude)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
  <div class="row">

   <div class="col-lg-10 col-md-10 ml-auto mr-auto">
    <h1 class="text-center">\ New Event /</h1>

    <div class="card p-5" style="width: 50rem;">
      <%= form_with(model: event, local: true) do |form| %>

        <% if event.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

            <ul>
            <% event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="date">
          <%= form.label :"日付をお選びください" %>
          <%= form.date_select :date %>
        </div><br>

        <div class="field">
            <%= form.label :"タイトル" %>
            <%= form.text_field :title, :size => "50x10" %>
        </div>

        <div class="field">
          <p>テキスト入力部分　(1000文字以内)</p>
          <%= form.text_area :body, :size => "100x20" %>
        </div>

        <%= attachment_image_tag @event, :picture, format: 'jpeg', class: "", fallback: "no_image.jpg", :size =>'150x100' %><br>

        <div class="field">
          <%= form.label :"イメージ写真" %>
          <%= form.attachment_field :picture %>
        </div><br>


        <div class="field">
          <%= form.label :"都道府県" %>
          <%= form.collection_select :prefecture_name, JpPrefecture::Prefecture.all,:name, :name, {:prompt => true}, class: 'form-control' %>
        </div>

        <div class="field">
          <%= form.label :"行われる場所/施設名" %>
          <%= form.text_field :address %>
        </div>


        <div class="actions">
          <%= form.submit %>
        </div>
      
      <% end %>
    </div>

   </div>

  </div>

app/views/events/edit.html.erb
<div class="container">
	<div class="form">

      <%= render 'form', event: @event %>

      <%= link_to 'イベント内容', @event, class: "btn btn-primary btn-sm ml-2" %>
      <%= link_to '戻る', events_path, class: "btn btn-primary btn-sm ml-2" %>

  </div>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="form">


  <div class="row">
    <div class="col-xs-12 center-block display-3">All Events</div>
  </div>

    <dev class="row">

     <div class="col-md-3">
      <%= render partial: '/home/mybox' %>
      <% if host_signed_in? %>
        <%= render partial: '/home/hostsbox', locals: {host: current_host} %>
      <% end %>
     </div>

      <div class="col-md-9 float-right">

          <table class="table table-striped">
　　　　　　　<tbody>
              <% @events.each do |event| %>
                <tr>
                  <td><%= link_to event do %>
                    <%= attachment_image_tag event, :picture, format: 'jpeg', class: "img-thumbnail", fallback: "no_image.jpg", :size =>'100x80' %></td>
                  <% end %>
                  <td><p><%= event.date %></p></td>
                  <td><p><%= event.title.truncate(10) %></p></td>
                  <td><p><%= event.prefecture_name %></p></td>
                  <td><p><%= event.address %></p></td>
                </tr>
              <% end %>
            </tbody>
          </table>

      </div>
    </dev>

  </div>
</div>

app/views/events/new.html.erb
<div class="container">
	<div class="form">

    <%= render 'form', event: @event %>

   <div class="row">
     <div class="col-lg-8 col-md-6 mr-auto mt-5 mb-5">
       <%= link_to 'イベント一覧へ', events_path, class: "btn btn-primary btn-sm ml-2"%>
     </div>
   </div>

    </div>
</div>

app/views/events/show.html.erb
<script type="text/javascript">
    function initMap() {

        var test ={lat: <%= @latitude %>, lng: <%= @longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: test
        });
        var transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);

        var contentString = '住所：<%= @address %>';
        var infowindow = new google.maps.InfoWindow({
            content: contentString
        });

        var marker = new google.maps.Marker({
            position:test,
            map: map,
            title: contentString
        });

        marker.addListener('click', function() {
            infowindow.open(map, marker);
        });
    }
</script>


<p id="notice"><%= notice %></p>

<div class="container">
  <div class="form">

    <dev class="row ">
      <div class="col-md-3">

        <%= render partial: '/home/mybox' %>
        <% if host_signed_in? %>
          <%= render partial: '/home/hostsbox', locals: {host: current_host} %>
        <% end %>
      </div>


      <div class="col-md-9 float-right">

        <dev class="row ">
          <div class="col-md-10 offset-md-1 mr-auto">
            <%= attachment_image_tag @event, :picture, format: 'jpeg', class: "rounded", fallback: "no_image.jpg", :size =>'800x500' %>
          </div>
        </dev><br>

        <div class="row">
              <div class="col-md-8">
                <div class="display-5 border-bottom">
                  <div class="text"><%= @event.title %></div>
                </div>
              </div>
              <div class="col-md-3">
                <h5>
                  <%= @event.date %>
                </h5>
              </div>
              <div class="col-md-1">
                <!-- 気になるボタンを追加/ -->
                <div id="joins_buttons_<%= @event.id %>">
                  <%= render partial: 'joins/join', locals: { event: @event, joins: @joins} %>
                </div>
              </div>
        </div>

        <div class="row">
              <div class="col-md-8 offset-md-2 mt-3">
                <div class="text">
                  <h5><%= @event.prefecture_name %> /  <%= @event.address %></h5><br>
                  <p><%= @event.body %></p>
                  <%= link_to host_path(@host) do %>
                    <p class="text-right border-bottom">イベント主催者 : <%= @host.group_name %></p>
                  <% end %>
                </div>
              </div>
        </div><br>


        <style type="text/css">
        #map { height: 400px;
        margin-left:auto;
        margin-right:auto;
        text-align:left;
        width: 80%;}
        </style>
        <div id="map"></div>

        <% if host_signed_in? %>
        <% if @event.host_id == current_host.id %>
          <%= link_to '内容を編集する', edit_event_path(@event), class: "btn btn-primary btn-sm mr-auto ml-auto mt-5 mb-5" %>
        <% end %>
        <% end %>
          <%= link_to '<< Events', events_path, class: "btn btn-primary btn-sm mr-auto ml-auto mt-5 mb-5" %>

      </div>
    </dev>

  </div>
</div>