config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#top'

 devise_for :hosts, controllers: {
  #get "sign_in", to: "devise/sessions"
  sessions:      'hosts/sessions',
  passwords:     'hosts/passwords',
  registrations: 'hosts/registrations'
}

  devise_for :users, controllers: {
   sessions: 'users/sessions',
   passwords: 'users/passwords',
   registrations: 'users/registrations'
}

  resources :users, only: [:show, :edit, :update]
  resources :hosts, only: [:show, :edit, :update]
  resources :events do
  resources :joins, only: [:create, :destroy]
  end
  resources :articles do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_pictures, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :users, through: :likes, source: :article
    accepts_attachments_for :article_pictures, attachment: :picture
    geocoded_by :address
    after_validation :geocode
    acts_as_taggable
    enum category:{report: 0,item: 1,coodinate: 2}
    attachment :main_picture
    with_options presence: true do
      validates :title, length: { maximum: 30 }
      validates :body, length: { maximum: 1000 }
      validates :main_picture
    end
    # ユーザーが持っているlikeモデルを探す
    def like_user(user_id)
        likes.find_by(user_id: user_id)
    end
    default_scope -> { order(created_at: :desc) }
    # 時間の降順に表示
end

app/models/article_picture.rb
class ArticlePicture < ApplicationRecord
	belongs_to :article
	attachment :picture
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :article
	validates :message, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  attachment :picture
  belongs_to :host
  has_many :joins, dependent: :destroy, foreign_key: 'Event_id'
  has_many :users, through: :joins, source: :event
  geocoded_by :address
  after_validation :geocode
  default_scope -> { order(date: :desc) }
  # 時間の降順に表示
  with_options presence: true do
    validates :title, length: { maximum: 30 }
    validates :body, length: { maximum: 1000 }
    validates :address
    validates :date
  end
  def join_user(user_id)
    joins.find_by(user_id: user_id)
  end

  include JpPrefecture
     jp_prefecture :prefecture_code
  #prefecture_codeからprefecture_nameに変換する
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/host.rb
class Host < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, dependent: :destroy

  validates :group_name, presence: true, length: { maximum: 15 }
  validates :rep_name, presence: true,  length: { maximum: 15 }
  validates :address, presence: true
  validates :phonenum, presence: true,  length: { maximum: 13 }
end

app/models/join.rb
class Join < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :event, counter_cache: :join_count
  validates :user_id, presence: true
  validates :event_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :article
	belongs_to :article, counter_cache: :like_count
	validates :user_id, presence: true
    validates :article_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  has_many :joins, dependent: :destroy
  has_many :events, through: :joins, source: :user, foreign_key: 'User_id'
  has_many :articles, dependent: :destroy
  has_many :articles, through: :likes, source: :user, foreign_key: 'User_id'
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :webname, presence: true, length: { maximum: 15 }
  validates :profile, length: { maximum: 100 }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host
  before_action :authenticate_host!, only: [:edit, :update]
def show
     @events = Event.where(host_id: @host.id).all
  end

  def edit
  end

  def update
    if current_host == @host

     if @host.update(host_params)
        flash[:success] = 'ユーザー情報を編集しました。'
        redirect_to host_path(@host)
      else
        flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
        render :edit
     end
    end
  end

  private
  def set_host
    @host = Host.find(params[:id])
  end
  def host_params
      params.require(:host).permit(:group_name, :rep_name, :address, :phonenum, :url, :email)
  end
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
	before_action :set_event
  
  def create
    @join =Join.create(user_id: current_user.id, event_id: params[:event_id])
    @joins = Join.where(event_id: params[:event_id])
    @event.reload
  end

  def destroy
    join =Join.find_by(user_id: current_user.id, event_id: params[:event_id])
    join.destroy
    @joins = Join.where(event_id: params[:event_id])
    @event.reload
  end

  private
  def set_event
  	@event = Event.find(params[:event_id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :set_article
  def create
  	@like = Like.create(user_id: current_user.id, article_id: params[:article_id])
    @likes = Like.where(article_id: params[:article_id])
    @article.reload
  end

  def destroy
  	like = Like.find_by(user_id: current_user.id, article_id: params[:article_id])
    like.destroy
    @likes = Like.where(article_id: params[:article_id])
    @article.reload
  end

  private
  def set_article
  	@article = Article.find(params[:article_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/joins/_join.html.erb
<% if user_signed_in? %>

  <% unless event.join_user(current_user.id).blank? %>
    <%= link_to event_join_path(event_id: event.id ,id: event.joins[0].id), method: :delete, remote: true do %>
      <div class="vertical-align-top">
        <i class="fas fa-thumbtack fa-2x text-warning"></i>
        <span class="orange-text">
          <%= event.join_count %>
        </span>
      </div>
    <% end %>
  <% else %>
    <%= link_to event_joins_path(event.id), method: :post, remote: true do %>
      <div class="vertical-align-top">
        <i class="fas fa-thumbtack fa-2x text-multed"></i>
        <span class="grey-text text-multed">
          <%= event.join_count %>
        </span>
      </div>
    <% end %>
  <% end %>

  <% else %>

  <% if event.join_count > 0 %>
    <div class="vertical-align-top">
      <i class="fas fa-thumbtack fa-2x text-warning"></i>
      <span class="orange-text">
        <%= event.join_count %>
      </span>
    </div>
  <% else %>
    <div class="vertical-align-top">
      <i class="fas fa-thumbtack fa-2x text-multed"></i>
      <span class="grey-text text-multed">
        <%= event.join_count %>
      </span>
    </div>
  <% end %>

<% end %>

app/views/joins/create.js.erb
$('#joins_buttons_<%= @event.id %>').html("<%= j(render partial: 'joins/join', locals: {event: @event}) %>");

app/views/joins/destroy.js.erb
$('#joins_buttons_<%= @event.id %>').html("<%= j(render partial: 'joins/join', locals: {event: @event}) %>");

app/views/likes/_like.html.erb
<% if user_signed_in? %>

  <% unless article.like_user(current_user.id).blank? %>
    <%= link_to article_like_path(article_id: article.id ,id: article.likes[0].id), method: :delete, remote: true do %>
      <div class="vertical-align-top">
        <i class="far fa-bookmark fa-2x text-danger"></i>
        <span class="orange-text">
          <%= article.like_count %>
        </span>
      </div>
    <% end %>
  <% else %>
    <%= link_to article_likes_path(article.id), method: :post, remote: true do %>
      <div class="vertical-align-top">
        <i class="far fa-bookmark fa-2x text-multed"></i>
        <span class="grey-text text-multed">
          <%= article.like_count %>
        </span>
      </div>
    <% end %>
  <% end %>

<% else %>

  <% if article.like_count > 0 %>
    <div class="vertical-align-top">
        <i class="far fa-bookmark fa-2x text-danger"></i>
      <span class="orange-text">
        <%= article.like_count %>
      </span>
    </div>
  <% else %>
    <div class="vertical-align-top">
        <i class="far fa-bookmark fa-2x text-multed"></i>
      <span class="grey-text text-multed">
        <%= article.like_count %>
      </span>
    </div>
  <% end %>

<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @article.id %>').html("<%= j(render partial: 'likes/like', locals: {article: @article}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @article.id %>').html("<%= j(render partial: 'likes/like', locals: {article: @article}) %>");